# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\github\project\CG.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1141, 1068)
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setBold(True)
        font.setWeight(75)
        Form.setFont(font)
        self.groupBox_5 = QtWidgets.QGroupBox(Form)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 0, 1321, 701))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 400, 231, 291))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.btn_plc = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_plc.setGeometry(QtCore.QRect(10, 60, 211, 41))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.btn_plc.setFont(font)
        self.btn_plc.setObjectName("btn_plc")
        self.btn_pls = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_pls.setGeometry(QtCore.QRect(10, 110, 211, 41))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.btn_pls.setFont(font)
        self.btn_pls.setObjectName("btn_pls")
        self.btn_plr = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_plr.setGeometry(QtCore.QRect(10, 160, 211, 41))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.btn_plr.setFont(font)
        self.btn_plr.setObjectName("btn_plr")
        self.btn_ply = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_ply.setGeometry(QtCore.QRect(10, 210, 211, 41))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.btn_ply.setFont(font)
        self.btn_ply.setObjectName("btn_ply")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_3.setGeometry(QtCore.QRect(280, 20, 1021, 331))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.po1 = QtWidgets.QGraphicsView(self.groupBox_3)
        self.po1.setGeometry(QtCore.QRect(20, 50, 482, 272))
        self.po1.setObjectName("po1")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(220, 20, 61, 21))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.po2 = QtWidgets.QGraphicsView(self.groupBox_3)
        self.po2.setGeometry(QtCore.QRect(520, 50, 482, 272))
        self.po2.setObjectName("po2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(730, 20, 61, 21))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox.setGeometry(QtCore.QRect(30, 60, 231, 291))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.btn_pos = QtWidgets.QPushButton(self.groupBox)
        self.btn_pos.setGeometry(QtCore.QRect(10, 110, 211, 41))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.btn_pos.setFont(font)
        self.btn_pos.setObjectName("btn_pos")
        self.btn_por = QtWidgets.QPushButton(self.groupBox)
        self.btn_por.setGeometry(QtCore.QRect(10, 160, 211, 41))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.btn_por.setFont(font)
        self.btn_por.setObjectName("btn_por")
        self.btn_poy = QtWidgets.QPushButton(self.groupBox)
        self.btn_poy.setGeometry(QtCore.QRect(10, 210, 211, 41))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.btn_poy.setFont(font)
        self.btn_poy.setObjectName("btn_poy")
        self.btn_poc = QtWidgets.QPushButton(self.groupBox)
        self.btn_poc.setGeometry(QtCore.QRect(10, 60, 211, 41))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.btn_poc.setFont(font)
        self.btn_poc.setObjectName("btn_poc")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_4.setGeometry(QtCore.QRect(280, 360, 1021, 331))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.pl1 = QtWidgets.QGraphicsView(self.groupBox_4)
        self.pl1.setGeometry(QtCore.QRect(20, 50, 482, 272))
        self.pl1.setObjectName("pl1")
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setGeometry(QtCore.QRect(220, 20, 61, 21))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pl2 = QtWidgets.QGraphicsView(self.groupBox_4)
        self.pl2.setGeometry(QtCore.QRect(520, 50, 482, 272))
        self.pl2.setObjectName("pl2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(730, 20, 61, 21))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.groupBox_8 = QtWidgets.QGroupBox(Form)
        self.groupBox_8.setGeometry(QtCore.QRect(20, 710, 601, 331))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_9.setGeometry(QtCore.QRect(20, 40, 271, 271))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.btn_voc = QtWidgets.QPushButton(self.groupBox_9)
        self.btn_voc.setGeometry(QtCore.QRect(50, 30, 171, 51))
        self.btn_voc.setObjectName("btn_voc")
        self.btn_vos = QtWidgets.QPushButton(self.groupBox_9)
        self.btn_vos.setGeometry(QtCore.QRect(50, 90, 171, 51))
        self.btn_vos.setObjectName("btn_vos")
        self.btn_vor = QtWidgets.QPushButton(self.groupBox_9)
        self.btn_vor.setGeometry(QtCore.QRect(50, 150, 171, 51))
        self.btn_vor.setObjectName("btn_vor")
        self.btn_voy = QtWidgets.QPushButton(self.groupBox_9)
        self.btn_voy.setGeometry(QtCore.QRect(50, 210, 171, 51))
        self.btn_voy.setObjectName("btn_voy")
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_10.setGeometry(QtCore.QRect(310, 40, 271, 271))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName("groupBox_10")
        self.btn_vlc = QtWidgets.QPushButton(self.groupBox_10)
        self.btn_vlc.setGeometry(QtCore.QRect(50, 30, 171, 51))
        self.btn_vlc.setObjectName("btn_vlc")
        self.btn_vls = QtWidgets.QPushButton(self.groupBox_10)
        self.btn_vls.setGeometry(QtCore.QRect(50, 90, 171, 51))
        self.btn_vls.setObjectName("btn_vls")
        self.btn_vlr = QtWidgets.QPushButton(self.groupBox_10)
        self.btn_vlr.setGeometry(QtCore.QRect(50, 150, 171, 51))
        self.btn_vlr.setObjectName("btn_vlr")
        self.btn_vly = QtWidgets.QPushButton(self.groupBox_10)
        self.btn_vly.setGeometry(QtCore.QRect(50, 210, 171, 51))
        self.btn_vly.setObjectName("btn_vly")
        self.groupBox_11 = QtWidgets.QGroupBox(Form)
        self.groupBox_11.setGeometry(QtCore.QRect(680, 720, 661, 321))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setObjectName("groupBox_11")
        self.textshow = QtWidgets.QTextBrowser(self.groupBox_11)
        self.textshow.setGeometry(QtCore.QRect(70, 50, 521, 241))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.textshow.setFont(font)
        self.textshow.setObjectName("textshow")

        self.retranslateUi(Form)
        self.btn_poc.clicked.connect(Form.poc)
        self.btn_pos.clicked.connect(Form.pos)
        self.btn_por.clicked.connect(Form.por)
        self.btn_poy.clicked.connect(Form.poy)
        self.btn_plc.clicked.connect(Form.plc)
        self.btn_pls.clicked.connect(Form.pls)
        self.btn_plr.clicked.connect(Form.plr)
        self.btn_ply.clicked.connect(Form.ply)
        self.btn_voc.clicked.connect(Form.voc)
        self.btn_vos.clicked.connect(Form.vos)
        self.btn_vor.clicked.connect(Form.vor)
        self.btn_voy.clicked.connect(Form.voy)
        self.btn_vlc.clicked.connect(Form.vlc)
        self.btn_vls.clicked.connect(Form.vls)
        self.btn_vlr.clicked.connect(Form.vlr)
        self.btn_vly.clicked.connect(Form.vly)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "郭子毓计算机图形学设计课项目——目标检测与车牌识别"))
        self.groupBox_5.setTitle(_translate("Form", "图像处理"))
        self.groupBox_2.setTitle(_translate("Form", "车牌识别"))
        self.btn_plc.setText(_translate("Form", "选择文件"))
        self.btn_pls.setText(_translate("Form", "SSD强化识别"))
        self.btn_plr.setText(_translate("Form", "Retinanet强化识别"))
        self.btn_ply.setText(_translate("Form", "YoloV3强化识别"))
        self.groupBox_3.setTitle(_translate("Form", "目标检测模型效果展示"))
        self.label.setText(_translate("Form", "Origin"))
        self.label_2.setText(_translate("Form", "Result"))
        self.groupBox.setTitle(_translate("Form", "目标检测"))
        self.btn_pos.setText(_translate("Form", "SSD检测"))
        self.btn_por.setText(_translate("Form", "Retinanet检测"))
        self.btn_poy.setText(_translate("Form", "YoloV3检测"))
        self.btn_poc.setText(_translate("Form", "选择文件"))
        self.groupBox_4.setTitle(_translate("Form", "车牌识别模型效果展示"))
        self.label_3.setText(_translate("Form", "Origin"))
        self.label_4.setText(_translate("Form", "Result"))
        self.groupBox_8.setTitle(_translate("Form", "视频处理"))
        self.groupBox_9.setTitle(_translate("Form", "目标检测"))
        self.btn_voc.setText(_translate("Form", "选择文件"))
        self.btn_vos.setText(_translate("Form", "SSD检测"))
        self.btn_vor.setText(_translate("Form", "Retinanet检测"))
        self.btn_voy.setText(_translate("Form", "YoloV3检测"))
        self.groupBox_10.setTitle(_translate("Form", "车牌识别"))
        self.btn_vlc.setText(_translate("Form", "选择文件"))
        self.btn_vls.setText(_translate("Form", "SSD检测"))
        self.btn_vlr.setText(_translate("Form", "Retinanet检测"))
        self.btn_vly.setText(_translate("Form", "YoloV3检测"))
        self.groupBox_11.setTitle(_translate("Form", "程序运行情况提示栏"))
        self.textshow.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'华文新魏\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
